# Base configs
baseurl: "https://www.felinara-ceramics.com"
#baseurl: "" # Comment the above line and uncomment this to test the website locally
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "G-QXBSWZF5TP"

# UI configs
title: "Ceramics by Felinara Ceramics"
subtitle: "See creations of ceramics through my eyes!"
author: "Brian Chew"
header:
 title: "Ceramics"
 subtitle: "by Brian Chew"
footer:
 name: "Hey there! Welcome to my ceramics journey"
 bio: |
    Casual ceramicist.
    Lately Iâ€™ve been loving the world of slip casting.
    To craft handmade ceramics that celebrate cats and inspire compassion, while supporting cat rescue and adoption.
#  github: ""
# web_design: "AJ"
# Configure which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks
# exif: '[{"tag": "Model", "icon": "camera-retro"}, {"tag": "FNumber", "icon": "dot-circle-o"}, {"tag": "ExposureTime", "icon": "clock-o"}, {"tag": "ISOSpeedRatings", "icon": "info-circle"}]'
social_urls:
  # twitter: "https://www.twitter.com/ram__patra"
  instagram: "https://www.instagram.com/felinara.ceramics"
  # dribbble: "https://dribbble.com/rampatra"
  # linkedin: "https://in.linkedin.com/in/ram-patra"
  # github: "https://www.github.com/rampatra"
